import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Button } from "@/components/ui/button";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={inter.className}>
        <header className="flex">
          <nav className="flex justify-between m-auto w-[80%]">
            <div>Logo</div>
            <div>
              <ul className="flex gap-20">
                <li>link2</li>
                <li>link3</li>
                <li>link4</li>
              </ul>
            </div>
          </nav>
          <Link href="/logout">Logout</Link>
        </header>
          {children}
      </body>
    </html>
  );
}
